services:
  postgres:
    build:
      context: ./db-service
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - ./db-service/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080

  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory
    ports:
      - "3001:3001"

  history-service:
    build:
      context: ./history-service
    container_name: history-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory
    ports:
      - "3002:3002"

